libcot: example_timer.c File Reference
example_timer.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <ptask.h>
#include <obix_client.h>
Defines
#define CONNECTION_ID 0
Functions
int resetListener (int connectionId, int deviceId, int listenerId, const char *newValue)
void generateTimeString ()
void timerTask (void *arg)
char * getDeviceData (char *deviceUri)
int main (int argc, char **argv)
Variables
const char * DEVICE_DATA
unsigned long _time
char _time_str [32]
pthread_mutex_t _time_mutex = PTHREAD_MUTEX_INITIALIZER
Task_Thread * taskThread
Detailed Description
This is simple oBIX Timer device implementation, which demonstrates usage of oBIX client library. It shows the time elapsed after timer was started or reset by user. Device registers itself at oBIX Server, regularly updates elapsed time on it and listens to updates of "reset" parameter. If someone changes "reset" to true, that elapsed time is set to 0.
Author:
Andrey Litvinov
Version:
1.0
Definition in file example_timer.c.
Define Documentation
#define CONNECTION_ID 0
ID of the connection which is described in configuration file.
Definition at line 21 of file example_timer.c.
Referenced by main(), and timerTask().
Function Documentation
void generateTimeString ()
Generates string representation of elapsed time according to xs:duration XML data type.
Definition at line 83 of file example_timer.c.
References _time, and _time_str.
Referenced by timerTask().
int main (int argc, char ** argv)
Entry point of the Timer application. It takes the name of the configuration file (use example_timer_config.xml).
See also:
example_timer_config.xml
Definition at line 149 of file example_timer.c.
References CONNECTION_ID, obix_dispose(), obix_loadConfigFile(), obix_openConnection(), obix_registerDevice(), obix_registerListener(), OBIX_SUCCESS, resetListener(), taskThread, and timerTask().
int resetListener (int connectionId, int deviceId, int listenerId, const char * newValue)
Handles changes of "reset" value. The function implements obix_update_listener() prototype and is registered as a listener of "reset" param using obix_registerListener(). If "reset" value is changed at oBIX server to "true" it will set it back to "false" and reset timer.
See also:
obix_update_listener(), obix_registerListener().
Definition at line 50 of file example_timer.c.
References _time, _time_mutex, OBIX_SUCCESS, and obix_writeValue().
Referenced by main().
void timerTask (void * arg)
Updates timer value and writes it to oBIX server. Implements periodic_task() prototype and is scheduled using ptask_schedule(). This method is executed in a separate thread that is why it uses _time_mutex for synchronization with resetListener() which sets timer to 0.
See also:
periodic_task(), ptask_schedule().
Parameters:
arg Assumes that a pointer to the device ID is passed here. Device ID is used for updating time value at the server.
Definition at line 113 of file example_timer.c.
References _time, _time_mutex, _time_str, CONNECTION_ID, generateTimeString(), OBIX_SUCCESS, and obix_writeValue().
Referenced by main().
Variable Documentation
unsigned long _time
Elapsed time is stored here.
Definition at line 30 of file example_timer.c.
Referenced by generateTimeString(), resetListener(), and timerTask().
pthread_mutex_t _time_mutex = PTHREAD_MUTEX_INITIALIZER
Need mutex for synchronization, because _time variable is accessed from two threads.
Definition at line 37 of file example_timer.c.
Referenced by resetListener(), and timerTask().
char _time_str[32]
Used for string representation of the timer value.
Definition at line 32 of file example_timer.c.
Referenced by generateTimeString(), and timerTask().
const char* DEVICE_DATA
Initial value:
    "<obj name=\"ExampleTimer\" displayName=\"Example Timer\" href=\"%s\">\r\n"
    "  <reltime name=\"time\" displayName=\"Elapsed Time\" href=\"%stime\" val=\"PT0S\" writable=\"true\"/>\r\n"
    "  <bool name=\"reset\" displayName=\"Reset Timer\" href=\"%sreset\" val=\"false\" writable=\"true\"/>\r\n"
    "</obj>"
Data which is posted to oBIX server.
Definition at line 23 of file example_timer.c.
Task_Thread* taskThread
Separate thread for timer value updating.
Definition at line 39 of file example_timer.c.
Referenced by main().