libcot: obix_client.h File Reference
obix_client.h File Reference
#include <ixml_ext.h>
Typedefs
typedef int(* obix_update_listener)(int connectionId, int deviceId, int listenerId, const char *newValue)
Enumerations
enum OBIX_ERRORCODE {
OBIX_SUCCESS = 0, OBIX_ERR_INVALID_ARGUMENT = -1, OBIX_ERR_NO_MEMORY = -2, OBIX_ERR_INVALID_STATE = -3,
OBIX_ERR_LIMIT_REACHED = -4, OBIX_ERR_BAD_CONNECTION = -5, OBIX_ERR_UNKNOWN_BUG = -100, OBIX_ERR_HTTP_LIB = -6
}
enum OBIX_DATA_TYPE {
OBIX_T_BOOL, OBIX_T_INT, OBIX_T_REAL, OBIX_T_STR,
OBIX_T_ENUM, OBIX_T_ABSTIME, OBIX_T_RELTIME, OBIX_T_URI
}
Functions
int obix_loadConfigFile (const char *fileName)
int obix_loadConfig (IXML_Element *config)
int obix_dispose ()
int obix_openConnection (int connectionId)
int obix_closeConnection (int connectionId)
int obix_registerDevice (int connectionId, const char *obixData)
int obix_unregisterDevice (int connectionId, int deviceId)
int obix_writeValue (int connectionId, int deviceId, const char *paramUri, const char *newValue, OBIX_DATA_TYPE dataType)
int obix_registerListener (int connectionId, int deviceId, const char *paramUri, obix_update_listener listener)
int obix_unregisterListener (int connectionId, int deviceId, int listenerId)
Detailed Description
Contains definitions for oBIX client library.
Author:
Andrey Litvinov
Version:
0.1
Definition in file obix_client.h.
Typedef Documentation
typedef int(* obix_update_listener)(int connectionId, int deviceId, int listenerId, const char *newValue)
Callback function, which is invoked when subscribed value is changed at the oBIX server.
ID arguments of the listener can be used to define which parameter was updated in case when one function is registered to handle updates of several parameters.
See also:
obix_registerListener()
Parameters:
connectionId ID of the connection from which the update is received.
deviceId ID of the device whose parameter was changed. If the parameter doesn't belong to any device which was registered by current client, than 0 will be passed.
listenerId ID of the listener which receives the event.
newValue New value of the parameter.
Returns:
The listener should return OBIX_SUCCESS if the event was handled properly. Any other returned value will be considered by library as an error.
Definition at line 108 of file obix_client.h.
Enumeration Type Documentation
enum OBIX_ERRORCODE
Error codes which are returned by library functions
Enumerator:
OBIX_SUCCESS Operation is completed successfully.
OBIX_ERR_INVALID_ARGUMENT Function received wrong input argument.
OBIX_ERR_NO_MEMORY Not enough memory to complete the operation.
OBIX_ERR_INVALID_STATE Library has invalid state.
OBIX_ERR_LIMIT_REACHED Allocated buffer for devices or listeners is full.
Todo:
Remove this error and enlarge arrays when needed.
OBIX_ERR_BAD_CONNECTION Error in communication with server.
OBIX_ERR_UNKNOWN_BUG Reserved for uncaught errors. If such error occurs, this is a bug.
OBIX_ERR_HTTP_LIB Error inside HTTP communication module.
Definition at line 55 of file obix_client.h.
Function Documentation
int obix_closeConnection (int connectionId)
Closes specified connection releasing all used resources. Also unregisters all devices and listeners which were registered using this connection.
Parameters:
connectionId ID of the connection which should be closed.
Returns:
OBIX_SUCCESS on success, error code otherwise.
Definition at line 508 of file obix_client.c.
References OBIX_SUCCESS.
Referenced by obix_dispose().
int obix_dispose ()
Releases all resources allocated by library. All registered listeners and devices are unregistered, all open connections are closed.
Returns:
OBIX_SUCCESS if operation is completed successfully, error code otherwise.
Definition at line 704 of file obix_client.c.
References http_dispose(), obix_closeConnection(), and OBIX_SUCCESS.
Referenced by obix_loadConfig().
int obix_loadConfig (IXML_Element * config)
Initializes library and loads connection setting from provided DOM structure. Unlike obix_loadConfigFile() it doesn't configure log system of the library. Unconfigured log writes all messages to stdout.
Todo:
Update description of obix_loadConfig() after adding log header to the library.
Parameters:
config DOM structure representing a configuration XML.
Returns:
OBIX_SUCCESS if the library initialized successfully, error code otherwise.
Definition at line 431 of file obix_client.c.
References obix_dispose(), OBIX_ERR_INVALID_ARGUMENT, OBIX_ERR_NO_MEMORY, and OBIX_SUCCESS.
Referenced by obix_loadConfigFile().
int obix_loadConfigFile (const char * fileName)
Initializes library and loads connection setting from XML file. Also sets up the logging system of the library.
Parameters:
fileName Name of the configuration file.
Returns:
OBIX_SUCCESS if the library initialized successfully, error code otherwise.
Definition at line 407 of file obix_client.c.
References OBIX_ERR_INVALID_ARGUMENT, obix_loadConfig(), and OBIX_SUCCESS.
int obix_openConnection (int connectionId)
Opens connection with oBIX server.
Parameters:
connectionId Connection ID which was specified in the loaded configuration file.
Returns:
OBIX_SUCCESS if connection is opened successfully, error code otherwise.
Definition at line 489 of file obix_client.c.
References OBIX_SUCCESS.
int obix_registerDevice (int connectionId, const char * obixData)
Posts the provided device information to the oBIX server.
Note:
Input data is not tested to conform with oBIX specification. Is is strongly recommended to provide displayName attribute to every object. Also attributes href and writable are obligatory for all device parameters which are going to be changed by the device driver or external oBIX server users. writable attribute should be set to true; href attribute should have a valid URI, relative to the parent object.
Example:
 <obj name="light" href="/kitchen/light/" displayName="Kitchen lights">
     <bool name="switch"
         href="switch/"
         displayName="Switch"
         is="obix:bool"
         val="true"
         writable="true"/>
 </obj>
Note:
Parent object can specify href attribute but the oBIX server can modify it (for instance, add prefix of the device storage), thus URI can't be used to refer to the device record. Use device ID instead.
Parameters:
connectionId ID of the connection which should be used.
obixData oBIX object representing the new device.
Returns:
>0 ID of the created device record;
<0 error code.
Definition at line 550 of file obix_client.c.
References OBIX_ERR_LIMIT_REACHED, OBIX_ERR_UNKNOWN_BUG, and OBIX_SUCCESS.
int obix_registerListener (int connectionId, int deviceId, const char * paramUri, obix_update_listener listener)
Registers listener for device parameter updates.
Overwrites existing listener if is called twice.
This method can be also used to subscribe for the updates of any objects stored at the oBIX server. In that case 0 should be provided as deviceId and paramUri should be relative to the server root.
Parameters:
connectionId ID of the connection which should be used.
deviceId ID of the device whose parameter should be monitored or 0 if the parameter doesn't belong to devices registered by this client.
paramUri URI of the parameter which should be monitored. It should be either relative to the device record like it was provided during device registration, or relative to the server root if changing parameter doesn't belong to devices registered by this client.
listener Pointer to the listener function which would be invoked every time when the subscribed parameter is changed.
Returns:
>=0 ID of the created listener;
<0 error code.
Definition at line 601 of file obix_client.c.
References OBIX_ERR_LIMIT_REACHED, OBIX_ERR_UNKNOWN_BUG, and OBIX_SUCCESS.
int obix_unregisterDevice (int connectionId, int deviceId)
Removes device record from the oBIX server. Also removes all listeners which were registered for this device.
Parameters:
connectionId ID of the connection which should be used.
deviceId ID of the device which should be removed.
Returns:
OBIX_SUCCESS if the device record is removed successfully, error code otherwise.
Definition at line 583 of file obix_client.c.
References OBIX_SUCCESS.
int obix_unregisterListener (int connectionId, int deviceId, int listenerId)
Unregisters listener of device parameter updates.
Parameters:
connectionId ID of the connection which should be used.
deviceId ID of the device whose parameter is now monitored or 0 if the parameter doesn't belong to devices registered by this client.
listenerId ID of listener to be removed.
Returns:
OBIX_SUCCESS if the listener is removed successfully, error code otherwise.
Definition at line 645 of file obix_client.c.
References OBIX_ERR_INVALID_ARGUMENT, and OBIX_SUCCESS.
int obix_writeValue (int connectionId, int deviceId, const char * paramUri, const char * newValue, OBIX_DATA_TYPE dataType)
Overwrites value of the specified device parameter at the oBIX server.
This function can be also used to change a value of any writable object at the oBIX server. In that case 0 should be provided as deviceId and paramUri should be relative to the server root.
Parameters:
connectionId ID of the connection which should be used.
deviceId ID of the device whose parameter should be changed or 0 if the parameter doesn't belong to devices registered by this client.
paramUri URI of the parameter. It should be either relative to the device record like it was provided during device registration, or relative to the server root if changing parameter doesn't belong to devices registered by this client.
newValue Text representation of the new value to be written.
dataType Type of data which is written to the server.
Returns:
OBIX_SUCCESS on success, negative error code otherwise.
Definition at line 676 of file obix_client.c.
References OBIX_SUCCESS.